Modified the code in order to support with IS 5.3.0
wso2-extensions/identity-inbound-auth-cas pull request #16
Opened 2017-07-27 09:01 UTC by Shakila

2017-07-28 01:12 UTC, malakasilva requested changes

2017-07-28 01:12 UTC, malakasilva commented on components/cas-client-webapp/src/main/webapp/WEB-INF/web.xml
> +            <param-value>https://localhost:8443</param-value>
Please explain the reasons for changing this?

2017-07-28 01:12 UTC, malakasilva commented on components/cas-inbound-authenticator/src/main/java/org/wso2/carbon/identity/sso/cas/processor/SPInitSSOAuthnRequestProcessor.java
> +import java.io.*;
Shall we avoid the *

2017-07-28 01:12 UTC, malakasilva commented on components/cas-inbound-authenticator/src/main/java/org/wso2/carbon/identity/sso/cas/processor/SSOLoginProcessor.java
> +            throw new FrameworkException("Unable to decode the service URL", e);
Can we verify with IS team if this is the best way to do this?

2017-07-28 01:12 UTC, malakasilva commented on components/cas-inbound-authenticator/src/main/java/org/wso2/carbon/identity/sso/cas/request/CASIdentityRequestFactory.java
> +import java.io.*;
Try to avoid * in import

2017-07-28 01:12 UTC, malakasilva commented on components/cas-inbound-authenticator/src/main/java/org/wso2/carbon/identity/sso/cas/request/CASIdentityRequestFactory.java
> +        Enumeration attributeNames = request.getAttributeNames();
With this are we removing needed elements as well?

2017-07-28 04:03 UTC, Shakila commented on components/cas-client-webapp/src/main/webapp/WEB-INF/web.xml
> +            <param-value>https://localhost:8443</param-value>
If we use 8080, https won't work on Mac.

2017-07-28 04:08 UTC, Shakila commented on components/cas-inbound-authenticator/src/main/java/org/wso2/carbon/identity/sso/cas/request/CASIdentityRequestFactory.java
> +        Enumeration attributeNames = request.getAttributeNames();
We remove non serialised attributes for now. Once they fix the issue in framework level, we need to remove this part from the authenticator.

2017-07-31 06:32 UTC, kesavany approved these changes

2017-07-31 07:24 UTC, malakasilva approved these changes

2017-07-31 07:35 UTC, merged